name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Use pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: '8'

    - name: List directory contents
      run: ls -la
      

    - name: Build
      run: pnpm build

    - name: Commit and push
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'action: build script'